name: sports_management_app
description: Mobile application for Sports Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^7.0.1
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env 